name: workflowToken

on:
  workflow_dispatch:
    
jobs:
  # The ServiceNow job no longer waits for a local build step to pass
  changeApproval:
    name: ServiceNow Change Approval
    runs-on: ubuntu-latest

    steps:     
      - name: ServiceNow Change Approval
        uses: ServiceNow/servicenow-devops-change@v6.1.0
        id: create
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'ServiceNow Change Approval'
          change-request: '{"setCloseCode":"true","attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment."}}'
          interval: '100'
          timeout: '3600'
          changeCreationTimeOut: '3600'
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
